[package]
name = "embedded-STM32F3DISCOVER"
version = "0.1.0"
authors = ["mateusz <mateusz@rustle.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
